application: geloge-lo
version: 1
runtime: python
api_version: 1

handlers:
- url: /test
  script: test.py

- url: /tool/adduser
  script: tool/adduser.py
- url: /tool/getuser
  script: tool/getuser.py
- url: /tool/addtweet
  script: tool/addtweet.py
- url: /tool/gettweet
  script: tool/gettweet.py
- url: /tool/deltweet
  script: tool/deltweet.py

- url: /internal/add_user_to_queue
  script: internal/add_user_to_queue.py

- url: /get_user_gelo.json
  script: get_user_gelo.py

- url: /get_timeline
  script: get_timeline.py
- url: /static
  static_dir: static
- url: .*
  script: main.py
