application: geloge-lo
version: 1
runtime: python
api_version: 1

handlers:
- url: /test
  script: test.py
- url: /incremental
  script: incremental.py
- url: /update
  script: update.py
- url: /login
  script: login.py
- url: /logincb
  script: logincb.py

- url: /oauth
  script: geloauth/twitter.py
- url: /oauth/twitter/login
  script: geloauth/twitter.py
- url: /oauth/twitter/callback
  script: geloauth/twitter.py
- url: /oauth/twitter/logout
  script: geloauth/twitter.py

- url: /tool/adduser
  script: tool/adduser.py
- url: /tool/getuser
  script: tool/getuser.py
- url: /tool/addtweet
  script: tool/addtweet.py
- url: /tool/gettweet
  script: tool/gettweet.py
- url: /tool/deltweet
  script: tool/deltweet.py
- url: /tool/rate_limit_status
  script: tool/rate_limit_status.py


- url: /api/update
  script: api/update.py
- url: /api/get_timeline
  script: api/get_timeline.py
- url: /api/get_hashtag
  script: api/get_hashtag.py

- url: /internal/add_user_to_queue
  script: internal/add_user_to_queue.py

- url: /get_user_gelo.json
  script: get_user_gelo.py

- url: /get_timeline
  script: get_timeline.py
- url: /static
  static_dir: static
- url: .*
  script: main.py
